package cookiejar

import (
	"bufio"
	"fmt"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"strings"
	"time"
)

type Jar struct {
	jar *cookiejar.Jar
}

func New() *Jar {
	jar, _ := cookiejar.New(nil)
	return &Jar{jar: jar}
}

func (j *Jar) LoadFromFile(filePath string) error {
	file, err := os.Open(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("cannot open cookie file: %v", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.Split(line, "\t")
		if len(parts) < 7 {
			continue
		}

		domain := parts[0]
		path := parts[2]
		secure := parts[3] == "TRUE"
		expires := time.Unix(parseInt(parts[4]), 0)
		name := parts[5]
		value := parts[6]

		if expires.Before(time.Now()) {
			continue
		}

		u := &url.URL{
			Scheme: "https",
			Host:   domain,
			Path:   path,
		}

		cookie := &http.Cookie{
			Name:     name,
			Value:    value,
			Path:     path,
			Domain:   domain,
			Secure:   secure,
			HttpOnly: true,
			Expires:  expires,
		}

		j.jar.SetCookies(u, []*http.Cookie{cookie})
	}

	return scanner.Err()
}

func (j *Jar) SaveToFile(filePath string, u *url.URL) error {
	file, err := os.Create(filePath)
	if err != nil {
		return fmt.Errorf("cannot create cookie file: %v", err)
	}
	defer file.Close()

	w := bufio.NewWriter(file)
	fmt.Fprintln(w, "# Netscape HTTP Cookie File")
	fmt.Fprintln(w, "# https://curl.haxx.se/rfc/cookie_spec.html")
	fmt.Fprintln(w, "# This file was generated by iurl")
	fmt.Fprintln(w)

	cookies := j.jar.Cookies(u)
	for _, cookie := range cookies {
		domain := cookie.Domain
		if !strings.HasPrefix(domain, ".") {
			domain = "." + domain
		}

		secure := "FALSE"
		if cookie.Secure {
			secure = "TRUE"
		}

		expires := cookie.Expires.Unix()
		if expires == 0 {
			expires = time.Now().Add(24 * time.Hour).Unix()
		}

		fmt.Fprintf(w, "%s\tTRUE\t%s\t%s\t%d\t%s\t%s\n",
			domain,
			cookie.Path,
			secure,
			expires,
			cookie.Name,
			cookie.Value,
		)
	}

	return w.Flush()
}

func (j *Jar) SetCookies(u *url.URL, cookies []*http.Cookie) {
	j.jar.SetCookies(u, cookies)
}

func (j *Jar) Cookies(u *url.URL) []*http.Cookie {
	return j.jar.Cookies(u)
}

func parseInt(s string) int64 {
	var n int64
	for _, c := range s {
		if c >= '0' && c <= '9' {
			n = n*10 + int64(c-'0')
		}
	}
	return n
}